### ISSUE TITLE
Playback of a capture is slow

### ISSUE THREAD

**Issue by humdingerb** [jackburton79/bescreencapture#8]
Playback of a screen capture with MediaPlayer is slow. My settings: file format AVI, codec MPEG-4 video. This is with v2.2.1 available from HaikuDepot.
MediaPlayer info says "132.000 fps", playback doesn't show a time, the time-slider-knob doesn't move. Terminal output says: MediaFileTrackSupplier: warning! track index 0 has no duration
I do realize this might be more an issue of Haiku's codecs... (hrev50749)

**Comment by jackburton79** [comment]
Hi Humdinger, is this on haiku x86_gcc2 or x86 ?

**Comment by humdingerb** [comment]
That's on gcc2hybrid.

**Comment by jackburton79** [comment]
And you are using the x86_gcc2 version, then ?
Anyway, I just tested on virtualbox (my only available haiku development platform, at the moment), and I can't reproduce the slowness problem. I can definitely reproduce the problem with older versions. So that's strange.
I could definitely reproduce the missing time and time-slider-knob-not-moving problems, but at the time I dismissed those issues as haiku bugs and did not bother.
I'll investigate a bit more.

**Comment by jackburton79** [comment]
By the way: with the gcc2 version installed from HaikuDepot I don't get the "MediaFileTrackSupplier: warning! track index 0 has no duration" output in the terminal, while I get it with the gcc4 version.
I think it's a bug of Haiku, though.

**Comment by jackburton79** [comment]
I tested with MediaConverter and could reproduce with it, too. So I opened a ticket on Haiku bugtracker to track the missing duration: #13190
